# Operadores basicos en Python
a = 5
b = 8

print(f'\nComparadores Basicos:')
print("------------------------------")
print(f'a = {a} y b = {b}')
print(f'a<b = {a<b}')
print(f'a>b = {a>b}')
print(f'a<=b = {a<=b}')
print(f'a>=b = {a>=b}')
print(f'a!=b = {a!=b}')
print(f'a==b = {a==b}')
print("------------------------------")
print(f'2 + 2 == 4 and 5 > 3 = {2+2==4 and 5>3}')
print("------------------------------")
print(f'2 + 2 == 4 or 5 > 3 = {2+2==4 or 5>3}')
print("------------------------------")
print(f'not 2 + 2 == 4 = {not 2 + 2 == 4}')
print("------------------------------")
print(f'False or False = {False or False}')
print("------------------------------")
print(f'False or True = {False or True}')
print("------------------------------")
print(f'False and False = {False and False}')
print("------------------------------")
print(f'not 3 + 3 > 2 * 3 = {not 3 + 3 > 2 * 3}')
print("------------------------------")
print(f'not 2 + 2 == 5 or 8 > 3 = {not 2 + 2 == 5 or 8 > 3}')
print("------------------------------")
print(f'not (2 + 2 == 5 or 8 > 3) = {not (2 + 2 == 5 or 8 > 3)}')
print("------------------------------")
print(f'5 * 2 > 9 and not 3 > 4 = {5 * 2 > 9 and not 3 > 4}')